name: sukimachi
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.3.1

  get_it: ^7.2.0

  google_fonts: ^2.3.1

  flutter_bloc: ^8.0.1
  table_calendar: ^3.0.5

  #url_launcher(flutterのアプリ内でWebサイトを表示したい時などに使用)
  url_launcher: ^6.0.20

  #Flutterアプリのランチャーアイコンを更新するタスクを簡素化するコマンドラインツール
  flutter_launcher_icons: ^0.9.2

  #crypto(Dartに実装された暗号化ハッシュ関数のセット)
  crypto: ^3.0.1

  #デフォルトのアイコンアセットのセットを含むアセットリポジトリ
  cupertino_icons: ^1.0.2

  auto_size_text: ^3.0.0

  flutter_svg: ^0.23.0+1

  #flutter_image_compress 画像をネイティブプラグインとして圧縮
  flutter_image_compress: ^1.1.0

  #extended_nested_scroll_view
  extended_nested_scroll_view: ^5.0.0

  #import_sorter (Dartのインポートを自動的に整理するDartパッケージ)
  import_sorter: ^4.6.0

  #responsive_builderレスポンシブ対応
  responsive_builder: ^0.2.0+2

  carousel_slider: ^4.0.0

  # Riverpod関連(状態管理)
  #riverpod コンパイル時にプログラミングエラーをキャッチ,オブジェクトをリッスン/結合するためのネストを削除,コードがテスト可能であることを確認します
  flutter_riverpod: ^1.0.3

  provider: ^6.0.2

  #flutter_hooks ライフサイクルを管理する新しい種類のオブジェクトです
  flutter_hooks: ^0.18.3

  #freezed
  freezed: ^1.1.1

  #JSONのシリアル化と逆シリアル化
  json_annotation: ^4.8.0

  #Firebase関連
  #firebase_core
  firebase_core: ^1.14.0

  #firebase_analytics(アプリの使用状況とユーザー エンゲージメントについて分析できるアプリ測定ソリューションです。)
  firebase_analytics: ^9.1.5

  #cloud_firestore(NoSQL クラウド データベースを使用して、クライアント側開発とサーバー側開発のデータを保存、同期する)
  cloud_firestore: 3.2.1

  #firebase_auth(パスワード、電話番号、一般的なフェデレーション ID プロバイダ（Google、Facebook、Twitter）などを使用した認証を行う)
  firebase_auth: ^3.3.14

  #firebase_storage(画像、音声、動画、またはその他のユーザーが生成したコンテンツを格納する)
  firebase_storage: ^10.2.12

  #cloud_functions
  cloud_functions: ^3.2.12

  #google_sign_in
  google_sign_in: ^5.3.2

  #go_router(Navigator2.0(宣言的な画面遷移)を簡単にする)
  go_router: ^3.1.1
  flutter_signin_button: ^2.0.0

  #fake_cloud_firestore(Repositoryをダミーデータで返却するのに利用)
  fake_cloud_firestore: ^1.2.2
  simple_logger: ^1.9.0

  # form_field_validate(カスタムのValidatorを作成したり、複数のValidatorを組み合わせるのに利用)
  form_field_validator: ^1.1.0

  #flutter_html HTMLとCSSをFlutterウィジェットとしてレンダリングするためのFlutterウィジェット
  flutter_html: ^2.2.1
  uuid: ^3.0.6

  universal_html: ^2.0.8

  #dropdown_button(ドロップダウンボタンのUIを良くするために利用)
  dropdown_button2: ^1.7.1
  firebase_auth_mocks: ^0.8.5+1
  google_sign_in_mocks: ^0.2.1
  image_picker_web: ^2.1.1
  cached_network_image: ^3.2.2
  path_provider: ^2.0.11
  flutter_linkify: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  import_lint: ^0.9.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
