name: Flutter_Analyzer

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  flutter_analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: subosito/flutter-action@v2.5.0
        with:
          channel: 'stable'
      - run: flutter pub get
      - name: Run Flutter format
        run: flutter format --set-exit-if-changed .
      - run: flutter test --no-test-assets --coverage --coverage-path=~/coverage/lcov.info
      - uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ~/coverage/lcov.info